### ISSUE TITLE
Roadtypes and Tramtypes size is 63 not 15 or 64

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#109]
*Current*

- OpenTTD provides for a shared pool of 63 Roadtypes and Tramtypes ("frosch: one id is used for 'no road/tram'")
- nml sizes Roadtype and Tramtype at 15 
  - https://github.com/OpenTTD/nml/blob/master/nml/actions/action0.py#L207
- NewGRF docs size Roadtypes and Tramtypes at 64
  - https://newgrf-specs.tt-wiki.net/wiki/Action0/Roadtypes
  - https://newgrf-specs.tt-wiki.net/wiki/NML:Roadtypes

This is a blocking issue and should be an easy fix.

*Desired*

- confirm that the OpenTTD pool is 63
- update nml to 63
- update docs to 63
- release nml 0.5.1

**Comment by FLHerne** [comment]
@frosch123 - are you sure they're shared?
According to the docs in landscape.html:

> Bits 5..0: Road roadtype, 0x3F for no road.
> Bits 11..6: Tram roadtype, 0x3F for no tram.

That's enough bits for each to have 64 IDs (or 63 and 'none'?) 

@PeterN must know...

**Comment by PeterN** [comment]
They're shared.

**Comment by glx22** [comment]
https://github.com/OpenTTD/OpenTTD/blob/1f1345de098294a4744981d0043512569a35102a/src/road.h#L197-L208
https://github.com/OpenTTD/OpenTTD/blob/1f1345de098294a4744981d0043512569a35102a/src/road_type.h#L32-L42

**Comment by andythenorth** [comment]
NFO and NML wiki pages updated to correct limit of 63.

**Comment by andythenorth** [comment]
Fixed by #110 and wiki docs changes, thanks all.
