### ISSUE TITLE
0.5.1 - animated forest tiles from OpenGFX+ Industries disappear

### ISSUE THREAD

**Issue by jrook1445** [OpenTTD/nml#140]
I'm using the animated forest industry tiles from OpenGFX+ Industries v6392 in Wannaroo Basic Industries.

On 0.5.0, all is ok, behaviour is as expected.

On 0.5.1, the sprites have disappeared and the forest industry is no longer visible in the main window.

I don't claim to understand how the animation code actually works, so unsure if something has been deprecated?

steps to reproduce: test newgrf attached

Linux Mint 19.3
nml 0.5.0, 0.5.1
PIL: 5.4.1
PLY: 3.11
python 3.5.2 (pyrun 2.2.3)
OpenTTD: 1.10.1

[ogfxinds-forest.tar.gz](https://github.com/OpenTTD/nml/files/4612187/ogfxinds-forest.tar.gz)

Edit - amended test newgrf

**Comment by FLHerne** [comment]
Nothing is supposed to have been deprecated in 0.5.1; this must be a bug of some kind.

**Comment by glx22** [comment]
Found the issue, Working on it.
