### ISSUE TITLE
Metric speed values are still slightly off

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/nml#147]
Using latest NML and OpenTTD there still seems to be something wrong with the metric speed units as mentioned in issue #74 and supposedly fixed in #75 . MPH works fine but KM/H values appear to be rounded wrong in OpenTTD despite being defined correctly in the NML code.

![Unnamed, 01_01_1990#2](https://user-images.githubusercontent.com/50259667/82174222-cd8e9500-9884-11ea-8c5e-b5ebfed3da79.png)

To check for yourself, load RattRoads (available on Bananas) and set the grf parameter "speed units" to km/h
Make sure your game setting "speed units" is also set to km/h and start a game
You should see the same result as shown above
Obviously the speeds should be 50 km/h, 60 km/h, 90 km/h, etc. but for some reason they are slightly off.

I also see a similar effect with m/s (but who really uses that anyway?)

**Comment by Eddi-z** [comment]
this is a bit tricky to achieve, as not all values are possible to represent, so some rounding has to occur

**Comment by FLHerne** [comment]
There's specific code to check that the final calculated value (in OTTD's units) converts/rounds back to the input value, and adjust it until it does.

(apparently not working, of course)
