### ISSUE TITLE
Converting railtypes under a train

### ISSUE THREAD

**Issue by TheGwyd** [OpenTTD/nml#162]
If you some how manage to get a train onto a rail tile where it has no power, you are unable to change the railtype underneath it, however if a train is powered on a rail tile you are able to convert it to other railtypes, where it can end up being not powered. It seems that this should work the other way around, to avoid get trains permanently stuck.

**Comment by TheGwyd** [comment]
This issue has been opened in the wrong place, apologies

**Comment by LordAro** [comment]
We can move issues!
