### ISSUE TITLE
NML erroring out when compiling

### ISSUE THREAD

**Issue by GreyfurWolf** [OpenTTD/nml#180]
NMLC under Win 10 on 64bit machine errors out with the below text:

"C:\NML>nmlc CSBusSetN4.5.5.nml
 nmlc ERROR: nmlc: An internal error has occurred:
nmlc-version: 0.5.0
Error:    (IndexError) "pop from empty list".
Command:  ['nmlc', 'CSBusSetN4.5.5.nml']
Location: File "nml\actions\action4.py", line 170, in get_string_action4s"

I have tried multiple versions, all do the same.

Link to NML file and lang files for review if needed:
https://www.dropbox.com/sh/r3coo1l9zw9wxn2/AAAXmVNYmRtnzJiZ2cEj7REua?dl=0

**Comment by glx22** [comment]
This error happens because you defined too many strings (the limit is 1024).
But the message could be more friendly.
