### ISSUE TITLE
NewGRF Town Names no longer compile after unknown changes

### ISSUE THREAD

**Issue by Gadg8eer** [OpenTTD/nml#184]
I am unable to compile FicTownNames Reloaded, and various other town name NewGRFs have been tested to also fail to compile under similar circumstances under nmlc 5.3...

`ERROR: "src/FicTownNames_R.nml", line 28: Not enough random bits for the town name generation (40 needed, 32 available)`

...but compile with no issues in nmlc 4.5, therefore I seem to have discovered an undocumented bug. If it's not a bug, and the bits are not meant to be used more than once, then I'm afraid you have made every sufficiently large town name GRF obsolete. Hopefully there's an easy fix for this?

I can provide my source code if needed, but it's a universal issue affecting all GRFs.

**Comment by Gadg8eer** [comment]
Oops, mistakenly clicked the close issue button.

**Comment by FLHerne** [comment]
The change responsible is #117, a fix for bug #116, introduced in 0.5.1.

`nmlc` definitely wasn't using enough random bits before in some cases, so it might not be possible to correctly compile this grf.

**Comment by Gadg8eer** [comment]
> 
> 
> The change responsible is #117, a fix for bug #116, introduced in 0.5.1.
> 
> `nmlc` definitely wasn't using enough random bits before in some cases, so it might not be possible to correctly compile this grf.

So then what's the idea? People have to compile town names with old versions of nmlc?

**Comment by glx22** [comment]
It just means the grf compiled with older version were actually broken and couldn't generate all expected names.

**Comment by FLHerne** [comment]
That said, the example here has 1600 or so single-part names. I know we need some magic to split those into ActionFs, but naïvely it seems 32 bits should be more than enough...

**Comment by glx22** [comment]
I could try to implement splitting, but I need a `nml` file to analyse and test.

**Comment by glx22** [comment]
I [modified townames regression nml](https://github.com/OpenTTD/nml/compare/master...glx22:townnames) to do some tests and it seems `nmlc` wastes bits. I think it would save 6 bits if it could determine that all options for `main` can share the same bit range. So I can easily imagine that being worse for huge grf.
