### ISSUE TITLE
check fails with new python3-pillow 8.1.0

### ISSUE THREAD

**Issue by david-geiger** [OpenTTD/nml#186]
Hi,

On Mageia Cauldron tests fails since new python3-pillow 8.1.0:

>   File "/usr/lib64/python3.8/site-packages/PIL/Image.py", line 1138, in crop
    self.load()
  File "/usr/lib64/python3.8/site-packages/PIL/ImageFile.py", line 284, in load
    raise_oserror(err_code)
  File "/usr/lib64/python3.8/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: buffer overrun when reading image file
make[1]: *** [Makefile:22: 006_vehicle] Error 1

Attached the full build log:
[build.0.20210123223203.log](https://github.com/OpenTTD/nml/files/5861922/build.0.20210123223203.log)

Regards,
David

**Comment by glx22** [comment]
Fixed with #182
