### ISSUE TITLE
nmlc doesn't throw an error when GRF name missing

### ISSUE THREAD

**Issue by EmperorJake** [OpenTTD/nml#194]
When you leave a GRF name out of the command, i.e. "nmlc --grf myfile.nml"  the program hangs on "Reading..." instead of throwing an error or giving the GRF a default name. If the command is entered incorrectly it should display an error because I incorrectly assumed it would work the same way as another program and wasted an embarrassing amount of time trying to fix it.

**Comment by nielsmh** [comment]
> 
> 
> It's reading from standard input and writing to a grf file named "myfile.nml", as invoked.

Suggest then improving the UI by changing the `Reading...` message into `Reading "filename.nml"...` or `Reading standard input...` depending on whether an input filename was given.
