### ISSUE TITLE
Internal NMLC error with GRF using a switch parameter

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/nml#197]
I am building a house set which heavily uses switches with parameters as functions. All have worked fine, except for calculating the town population using the parent scope and a parameter for the population required to construct the building. This returns an internal NMLC error.

![nmlc_error](https://user-images.githubusercontent.com/55058389/112637509-a09bfe80-8e14-11eb-8474-63005150258b.PNG)

I have attached a simple NML file which reproduces this error. Removing the parameter and changing the evaluation to a constant `population >= 10` compiles fine.
[error_grf.zip](https://github.com/OpenTTD/nml/files/6212013/error_grf.zip)

I compiled my copy of NMLC late last fall, I believe around the end of November.

**Comment by LordAro** [comment]
Can confirm.

https://github.com/OpenTTD/nml/blob/325164649a7c9f9ac2a9ad5c482643d66737af67/nml/actions/action2var.py#L942

At that point, `layout.register_map` only contains key/feature 20

Not that I've any idea where 7 or 20 came from...

**Comment by Eddi-z** [comment]
Feature 7 is Houses and feature 14 (20 dec) is towns

**Comment by FLHerne** [comment]
@frosch123 fixed this in #175.

Specifically it works after commit cf57433 "Fix: register_map must be accessed with the feature of the action, not with the scope of the variables."

**Comment by 2TallTyler** [comment]
Thanks! I'll update my NMLC.
