### ISSUE TITLE
Possible misnamed constant in global variable `map_type` 

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/nml#201]
Global variable `map_type` includes three options:
https://github.com/OpenTTD/nml/blob/5f25e4d2afb60c9816d36cf3363782b4753fdf9e/nml/global_constants.py#L644-L647

Since this option is returned when x==y, shouldn't `MAP_TYPE_RECTANGULAR` actually be `MAP_TYPE_SQUARE`?

**Comment by glx22** [comment]
From newgrf spec:
```
the type of map
- bit 0 set: squared map. Clear : rectangular map
- bit 1 set: Y is the bigger edge(bit 0 is clear). Clear : X is the bigger edge.
```
So yes, seems naming is wrong.
