### ISSUE TITLE
abs builtin function generates excessively verbose varaction2 output

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/nml#253]
At present the abs builtin function is implemented as:
`abs(x) --> (x < 0) ? (0 - x) : x`

If x happens to be some long or expensive calculation/variable access, it gets pasted into the output 3 times and executed at run-time 3 times.
The documentation for the abs function does not hint that it is so expensive and without inspecting the output GRF authors would have no reason to suspect that it is.

Suggestions:
1. STO_TMP and variable 7D should be used such that only one copy is required of the input

or

2. A shorter non-ternary sequence should be used such as: STO_TMP, CMP with constant 0, SUB constant 1, MUL var 7D

**Comment by glx22** [comment]
I think the same might happen with some other builtins.
