### ISSUE TITLE
Object company_colour variable points to wrong NFO variable number

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/nml#256]
https://github.com/OpenTTD/nml/blob/master/nml/actions/action2var_variables.py#L657-L658
animation_frame and company_colour are both mapped to the same bits of var 43, which seems wrong.
See also: https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Objects#Animation_Counter_.2843.29

The only colour variable is 47 (object colour) which does not have a corresponding NML variable, but this is not really a _company_ colour either.

**Comment by frosch123** [comment]
Industries have a `colour` variable. I think that name would also fit here.
