### ISSUE TITLE
version_openttd needs adjusting for OpenTTD >= 12

### ISSUE THREAD

**Issue by frosch123** [OpenTTD/nml#295]
`version_openttd` still follows the old 1.x.y versioning schema of OpenTTD.

People started working around this by testing for 1.12, 1.13, 1.14 instead for 12.0, 13.0 and 14.0: https://newgrf-specs.tt-wiki.net/index.php?title=NML:General&curid=340&diff=4465&oldid=4261

But this will only work till 15.0.
For 16.0 one would need `version_openttd(0, 16+16, 0)`, which is even more weird.

**Comment by planetmaker** [comment]
How does OpenTTD report its version now in variable 21/A1? According to the specs, it has only one nibble reserved:
https://newgrf-specs.tt-wiki.net/wiki/GlobalVariables#OpenTTD_Version_.2821_.2F_A1.29

**Comment by frosch123** [comment]
Ah, not even the NFO docs were updated :)
Anyway, meanwhile I made a PR #296
