### ISSUE TITLE
Wrong variable 'traffic_side'

### ISSUE THREAD

**Issue by kiwitreekor** [OpenTTD/nml#36]
VarAction2 variable 0x06 is 0x10 when traffic side is right, not 0x01.

**Comment by Eddi-z** [comment]
i don't see why you think it's wrong.

the variable `traffic_side` is not `VarAction2 variable 0x06`, but `VarAction2 variable 0x06, bit 4`, and thus the valid values are `0` and `1`. also, you're meant to check against `TRAFFIC_SIDE_LEFT` and `TRAFFIC_SIDE_RIGHT` and not be bothered with the numeric values.

**Comment by Eddi-z** [comment]
i see it now...
