### ISSUE TITLE
Document how to release nmlc, including building a windows binary

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#42]
**Current**

Releasing nml is mostly quite simple, and it would be suitable for drive-by releases by anyone with OpenTTD commit rights.

But how to release nml is not documented anywhere I can find.

This makes it harder than it needs to be.

_Additionally_ I don't know if it's known how to provide the Windows .exe binary reproducibly.  

**Desired**

- provide a list of the key points to cover when releasing nml
- document how to provide the Windows binary (or alternatively, it might be that we can drop the binary?)

Instructions should be added to a COMPILING.md file in repo root (this file needs creating).

**Comment by andythenorth** [comment]
Discussion here http://webster.openttdcoop.org/?channel=openttd&date=1571443200#1571515158

**Comment by andythenorth** [comment]
> frosch123: install msys2 and python3
> frosch123: msys2 has a python3 package
> frosch123: when you have that and pip, you can pip pyinstaller
> frosch123: oh, nml has cx_freeze specific code
> frosch123: so, better to use cx_freeze directly
> frosch123: anyway, if cx_freeze is installed and knows the compiler and stuff, it's just a "cxfreeze nmlc", and then zipping the results

**Comment by andythenorth** [comment]
#51 updates cx_Freeze support in setup.py

**Comment by matthijskooijman** [comment]
I have a related question: Where will releases be published? The (source) tarball was always uploaded to bundles.openttdcoop.org, but now development moved to github, where will release tarballs end up? I need to know this for the Debian package, so Debian can automatically check for newer versions.

**Comment by planetmaker** [comment]
I recon they still will be published on the same URL

**Comment by matthijskooijman** [comment]
Thanks, then I will leave the watch file unchanged :-)

**Comment by glx22** [comment]
Self containing windows executable is very easy to create now. You need `pyinstaller` module, then you can run `build-dist.bat`. The executable will be in dist.

**Comment by andythenorth** [comment]
Following #93, release process will be similar to OpenGFX (with some changes) https://github.com/OpenTTD/OpenGFX/blob/master/README.md#46-making-an-opengfx-release

**Comment by andythenorth** [comment]
#93 is merged, I should update the readme to add release instructions.

**Comment by andythenorth** [comment]
See #99
