### ISSUE TITLE
Release nml 0.5.x to provide NotRoadTypes support for nml authors

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#43]
**Current**

The PR for NotRoadTypes support is merged to master https://github.com/OpenTTD/nml/pull/30  We also have changes for 16 cargo industry support which are not in a released nml version.

* no release has been made including these changes
* the nml wiki docs are not updated for NRT - see #46

**Desired**

* release nml 0.5.x, including Windows binary - see also #42 
* updated wiki docs for NRT - see #46

**Comment by matthijskooijman** [comment]
I would also like to see a release for the fix to #52, which was reported in Debian. I can backport the fix, but there is a lot more changes in master that are probably useful to make available.

**Comment by andythenorth** [comment]
#52 is fixed.  #99 adds instructions on how to release to README.
