### ISSUE TITLE
Move nml docs to be in repo, build with jekyll/sphinx/readthedocs etc

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#44]
**Current**

nml docs are in the newgrf wiki

Upsides of the wiki:
- docs can be fixed independent of nml releases
- anyone can contribute
- in same place as nfo docs and general newgrf information
- searchable

Downsides of the wiki:
- documentation is divorced from  PRs that add features to nml
  - docs often define what the spec is 
  - absence of docs makes reviewing harder
- wiki cannot provide docs for unreleased features
  - makes it hard to get feedback / pre-release testing from newgrf authors

Contentious bits:
- I don't like wiki markup
- .md and friends have won for documenting code and libraries, wikis are just not as good for this use case

**Desired**

- replace wiki for nml with docs in the repo
- use .md or .rst whichever is considered to be winning
- leave the wiki in place for nfo and general newgrf info

- build and hosting options:
  - jekyll (native github) and use github pages (faff when I tried - requires weird set up)
  - sphinx and hosted https://readthedocs.org/
  - our own parser and push to S3 bucket or or coop bundles or digital ocean or something

**Comment by andythenorth** [comment]
There might be automated wiki scrapers to do this, or maybe it can just all be rebuilt by copy-paste.  Job for long winter evenings 👍

**Comment by MinchinWeb** [comment]
Since the rest of the code is in Python, Sphinx might be a good option. (Sphinx is also written in Python, Jekyll is in Rub.) It should be possible through GitHub actions to build the documentation, and then push it to GitHub pages (effectively the "gh-pages" branch of this repo) and host it from there. I've done this with previous project via Travis-CI, but haven't tried yet with GitHub Actions.

**Comment by nielsmh** [comment]
I'd be in favour of not using an automated tool to convert the docs, but do it manually. I don't particularly like the structure on the wiki and many sections (especially regarding basic syntax) seem unclear or even incomplete to me.

Also, while Markdown is popular, I think we should consider just writing things directly as HTML. Publishing will be a simple file copy (or upload). It will be readable, with formatting, unmodified on any user's computer. The documentation does use lots of tables which are IMHO annoying to work with in MD.

**Comment by Alberth289346** [comment]
asciidoc is nice, it is Eclipse documentation standard, comes close to expressiveness of Sphinx with simpler syntax.

`asciidoctor` is a popular implementation, manual at https://asciidoctor.org/docs/user-manual/

**Comment by andythenorth** [comment]
TMWFTLB
