### ISSUE TITLE
Update nml wiki docs for NotRoadTypes (NRT)

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#46]
**Current**

NRT support is merged in #30 

The nml wiki docs have not been updated with for NRT.
https://newgrf-specs.tt-wiki.net/wiki/NML:Main

**Desired**

Update the nml wiki docs for NRT.
- props
- vars
- callbacks
- type tables

Also note that the nfo docs are incomplete for NRT for multiple action types.
https://newgrf-specs.tt-wiki.net/wiki/Main_Page

**Comment by andythenorth** [comment]
A lot of this is done, see tracking table https://wiki.openttd.org/NewGRF_Specification_Status

**Comment by andythenorth** [comment]
Done.

**Comment by glx22** [comment]
Some pages still need to be updated:
- [ ] https://newgrf-specs.tt-wiki.net/wiki/NML:Switch
- [ ] https://newgrf-specs.tt-wiki.net/wiki/NML:Random_switch (after #92)

**Comment by andythenorth** [comment]
I will do this

**Comment by andythenorth** [comment]
[x]  https://newgrf-specs.tt-wiki.net/wiki/NML:Switch
[ ]  https://newgrf-specs.tt-wiki.net/wiki/NML:Random_switch

**Comment by andythenorth** [comment]
Done?
