### ISSUE TITLE
GRF integer parameters can be given negative values.

### ISSUE THREAD

**Issue by spnda** [OpenTTD/nml#57]
When giving a grf parameter a negative value, the compiler doesn't complain. Though OpenTTD has an assertion check to see if the values of the dropdown are positive.

Example:
```
min_value: -1;
max_value: 1;
def_value: 0;
```

![Image of Yaktocat](https://cdn.discordapp.com/attachments/442748131898032138/645287362208858122/unknown.png)

A zip containing the .grf and the .nml file.
[grf.zip](https://github.com/OpenTTD/nml/files/3854384/grf.zip)

Not sure, but maybe this is a OpenTTD related issue. This issue exists in various versions of OpenTTD, aswell as in JGR.

**Comment by LordAro** [comment]
Definitely an OpenTTD issue, should not be able to crash the game like that :p

**Comment by spnda** [comment]
Hmm true. Should this maybe be reopened as a issue on OpenTTD/OpenTTD?

**Comment by LordAro** [comment]
It should, but I'd say it's a valid issue that nml allows it as well
