### ISSUE TITLE
Why is Pillow >= 5.2 required?

### ISSUE THREAD

**Issue by matthijskooijman** [OpenTTD/nml#58]
Since #29, the README documents a minimum required Pillow version of 5.2. However, running some tests with version 3.4 seems to work just fine?

To test, I modified `setup.py` to remove the version constraint, then downgraded Pillow using `pip install Pillow=3.4.0`. Then I ran the regression tests (`make all` in the regression directory) and built OpenGFX, both of which completed without apparent problems.

@LordAro, you originally requested to add this constraint, perhaps you can comment?

**Comment by LordAro** [comment]
No real reason as best as I can tell. I think my comment was based on the assumption that PILLOW_VERSION was only added in 5.2, which it doesn't look like is the case. Certainly not the case now that `__version__` is used, anyway

**Comment by andythenorth** [comment]
So shall I edit the README to 3.4?  

I'm not going on a bisection mission to find the lowest compatible version, but I am happy to edit README to say 3.4

FWIW, I'm on Pillow 7.0.0, but that's neither here nor there :P

**Comment by matthijskooijman** [comment]
Perfect, thanks!
