### ISSUE TITLE
nfo output is slow with pypy

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#76]
nmlc is generally faster with pypy than python 3.8

However output to nfo is specifically about 5x slower with pypy compared to python 3.8.  

This appears to be due to poor performance of StringIO, which is a known issue with pypy: https://bitbucket.org/pypy/pypy/pull-requests/132/speed-up-pickledumps-fixes-issue-979

I created a test substituting StringIO with simple list append / join, which performs much faster
https://github.com/andythenorth/nml/commit/b2c9338d19fc7b1ca8e72a056bc25ba9abe232b9

For Iron Horse compile the difference is ~10s with pypy vs ~2s with python 3.8.  In the slower version the extra 8s represents ~25% of total compile time for the grf, so it is not insignificant.

My patch is not a viable candidate for merging, but this would be a helpful issue to fix.

**Comment by andythenorth** [comment]
FLHerne has a patch which substantially reduces output time with pypy in Iron Horse and FIRS compiles http://www.flherne.uk/files/nicer-quick-output.diff

**Comment by andythenorth** [comment]
I ran some tests against http://www.flherne.uk/files/nicer-quick-output.diff using [Iron Horse](https://github.com/andythenorth/iron-horse/commit/889de44cc3d6a82030603524f095444e66d0dedf and nml at rev 660722b680fd6a6c5b421d8eabbf36fcc82635ba
) 

Timings are purely for 'Writing output' step, tested over a couple of runs, with primed caches.

**Python 3.8**
 
Without patch: ~1.5s
With patch: ~1.7s - but also note there's an ignored Exception "FileNotFoundError: [Errno 2] No such file or directory: './generated/iron-horse.nfo.e5kf2jss.nmltemp'"

**PyPy"

Without patch: ~6.0s
With patch: ~1.0s

**Comment by FLHerne** [comment]
The slow performance of StringIO is fixed in PyPy 7.3.1.
