### ISSUE TITLE
No support for NRT tunnels

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/nml#79]
Currently the NML language has no support for providing tunnel sprites for roadtypes or tramtypes. Inclusion of both the "tunnels" and "tunnel_overlay" callbacks for these features would be ideal to allow authors to complete their NRT NewGRFs in time for OpenTTD 1.10.

**Comment by andythenorth** [comment]
Original frosch spec includes tunnels.  https://wiki.openttd.org/Frosch/NotRoadTypes#Tunnel

I don't see tunnels in the nfo spec or https://wiki.openttd.org/NewGRF_Specification_Status#OpenTTD_1.10

I'll explore further.

**Comment by glx22** [comment]
I don't see any use of overlays when a road tunnel portal is drawn
https://github.com/OpenTTD/OpenTTD/blob/b769eb30c43ccbc4e60b8b7df024253ac55d2265/src/tunnelbridge_cmd.cpp#L1264-L1274
So NML can't support a non existing feature ;)

**Comment by andythenorth** [comment]
@glx22 so is your conclusion that there's no support in OpenTTD for custom road (or tram) tunnel sprites?  

That's my understanding, from reading src.  

OpenTTD ticket needed?

**Comment by glx22** [comment]
BTW example on https://newgrf-specs.tt-wiki.net/wiki/NML:Roadtypes is wrong, there's no "tunnels" callback

**Comment by andythenorth** [comment]
> BTW example on https://newgrf-specs.tt-wiki.net/wiki/NML:Roadtypes is wrong, there's no "tunnels" callback

Thanks, fixed.

**Comment by frosch123** [comment]
Roadtypes do not include tunnels for the same reason they do not include bridges and stations.
On one tile there can be both road and tram, but only one tunnel/bridge/station.
Tunnels would be part of https://wiki.openttd.org/Frosch/ButGroundTypes , but NRT they make no sense.

**Comment by Andrew350** [comment]
@frosch123 Ok, so the idea was that roadtypes were not going to have the ability to provide custom tunnel entrances like railtypes do, in favor of waiting for a whole new schema of ground types? I love the spec proposed there, but with all due respect it sounds like another huge project which is years away. Meanwhile NRT is already going "live" in a month or so, and it would be nice in the meantime to at least have a basic implementation to provide some custom tunnel sprites similar to railtypes. Is that at least open to consideration?

**Comment by andythenorth** [comment]
For NRT tunnels, the blocker is that there's no rationale for determining whether to draw the tram tunnel, the road tunnel, or overlap sprites for both on the same tile. :)
 
If both the road type and the tram type on the tile provide tunnel sprites, I can't envisage that looking good.

With catenary, both the road type and the tram type can provide the sprites, and authors need to make sure that doesn't look bad by keeping catenary sprites simple so they can be combined.  That's going to fail sometimes, but at least it allowed NRT to be implemented.

But for tunnels I can't figure out a way to use the same approach and have any hope of a good result :)

**Comment by Andrew350** [comment]
Ok, I guess I can understand the issue with drawing the portals, so how about a callback for just the road/tram surfaces, not including the "structure"? That is definitely in-scope of NRT and doesn't involve any conflict of which sprite to draw over another. 

That at least would allow for some very basic control of tunnels for NRT authors until something better comes along :)

**Comment by frosch123** [comment]
Tunnels already draw the normal road/tram overlay, just like rail types also do. Why would they need to be different?

**Comment by Andrew350** [comment]
Tunnel portals are quite narrow, so the normal road tiles sometimes overlap the sides of the tunnel (essentially the same reason why bridges have special overlay sprites, to make them "fit") . It would also allow for shadows/lighting inside the tunnel for better effect, and just to make things prettier in general :)

**Comment by PikkaBird** [comment]
+1 to this request, just being able to use a different overlay sprite for the road in the tunnel entrance would be 95% of the way there, even without different portals.

> Tunnels already draw the normal road/tram overlay, just like rail types also do. Why would they need to be different?

The road in the tunnel may need to be narrower, different marked, shaded, etc. That's why we have the option to provide different (or no) overlays for rail types.

**Comment by EmperorJake** [comment]
It seems silly and inconsistent for railtypes to be able to provide their own tunnel portal sprites, but not roadtypes. It would be nice to specify different tunnel graphics for modern highways, old dirt roads, and metro tram tracks for example, just like you see in railtype GRFs with modern high speed lines, old branchlines and metro tracks.

As for the problem of which tunnel gets drawn in cases of both road and tram, simply draw the road tunnel if a road or road+tram is present, and draw the tram tunnel when only the tram track is present.

**Comment by EmperorJake** [comment]
The fact that this grahical issue is not solvable seems like a bug. It also has nothing to do with the tunnel portal itself necessarily, as the provision of a custom road overlay would be enough to solve it. Please reconsider adding this feature to the NRT spec.

![image](https://user-images.githubusercontent.com/68182631/230769507-ba34bb53-5b2d-4fe7-8278-8a896567be04.png)
