### ISSUE TITLE
openttd_version: OpenTTD var 21/1A result has changed since OpenTTD moved to git

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/nml#80]
See https://newgrf-specs.tt-wiki.net/wiki/GlobalVariables#OpenTTD_Version_.2821_.2F_A1.29

When OpenTTD was versioned using SVN the lower bits of var 21/A1 contained the SVN revision. Since OpenTTD 1.9 these bits are unused.  

nml has openttd_version var.  It also has a built-in function version_openttd(MAJOR, MINOR, BUILD, REVISION) which can test for a specific svn version of OpenTTD.  That won't return valid results with OpenTTD >= 1.9

**Comment by nielsmh** [comment]
The SVN revision bits are frozen to one past the last SVN revision number, they are not zero.
There are also AI and GS that depend on the version number, repurposing it will at the very least make sure it remains greater than the final SVN revision.

**Comment by andythenorth** [comment]
So is any change needed, other than updating nml docs?

**Comment by nielsmh** [comment]
I doubt it. See also https://github.com/OpenTTD/OpenTTD/pull/6843

**Comment by andythenorth** [comment]
So note here that svn version is no longer useful after a specific OpenTTD rev (which?) https://newgrf-specs.tt-wiki.net/wiki/NML:General

**Comment by planetmaker** [comment]
r28004 seems the last SVN rev. I added as much to the wiki... not sure what OpenTTD code says though.

**Comment by nielsmh** [comment]
Yes, 28004 is the hardcoded "final" SVN revision.
https://github.com/OpenTTD/OpenTTD/blob/4552b17691fa7c4f1fdb4ca7652ca48278a68fec/src/rev.cpp.in#L70-L83

**Comment by andythenorth** [comment]
Thanks, so the nml docs are accurate "only valid until OpenTTD r28004 / 1.9.0. In later versions the revision is fixed".  The wording there could be improved for clarity, I'll do that now.

**Comment by andythenorth** [comment]
Done
